/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UserController;
import javax.swing.*;

/**
 *
 * @author pappu
 */
public class LoginForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());
    private static UserController userController = new UserController();

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void handleLogin() {
        String email = txtEmail.getText().trim();
        String password = new String(fieldPassword.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter both email and password!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (userController.loginUser(email, password)) {
            JOptionPane.showMessageDialog(this,
                    "Login successful! Welcome " + userController.getCurrentUser().getName(),
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Invalid email or password!",
                    "Login Failed",
                    JOptionPane.ERROR_MESSAGE);
            fieldPassword.setText("");
        }
    }

    public static UserController getUserController() {
        return userController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgPanel = new javax.swing.JPanel();
        lftPanel = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        lblWlcm = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        lblForgt = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        btnNoAcc = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        iconRight = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgPanel.setBackground(new java.awt.Color(10, 20, 40));

        lftPanel.setBackground(new java.awt.Color(10, 20, 40));
        lftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setBackground(new java.awt.Color(20, 35, 60));
        btnRegister.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 204, 255));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/register.png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 200, 255), 2));
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setFocusPainted(false);
        btnRegister.setIconTextGap(15);
        btnRegister.setOpaque(true);
        btnRegister.setPreferredSize(new java.awt.Dimension(80, 240));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        lftPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 40));

        lblWlcm.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        lblWlcm.setForeground(new java.awt.Color(170, 230, 255));
        lblWlcm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcm.setText("WELCOME");
        lftPanel.add(lblWlcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 31));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ChatGPT Image Jan 5, 2026, 08_08_07 PM.png"))); // NOI18N
        lftPanel.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 560));

        rightPanel.setBackground(new java.awt.Color(10, 20, 40));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Serif", 1, 32)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(230, 245, 255));
        lblLogin.setText("Log In");
        rightPanel.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 258, 40));

        lblEmail.setFont(new java.awt.Font("SansSerif", 1, 21)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(200, 230, 255));
        lblEmail.setText("Email");
        rightPanel.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 78, 258, 35));

        txtEmail.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        rightPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 125, 290, 38));

        lblPassword.setFont(new java.awt.Font("SansSerif", 1, 21)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(200, 230, 255));
        lblPassword.setText("Password");
        rightPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 175, 258, 35));

        fieldPassword.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        rightPanel.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 222, 290, 37));

        lblForgt.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblForgt.setForeground(new java.awt.Color(140, 210, 255));
        lblForgt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblForgt.setText("Forgot Password");
        lblForgt.setToolTipText("");
        lblForgt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightPanel.add(lblForgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 140, -1));

        loginBtn.setBackground(new java.awt.Color(10, 30, 70));
        loginBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Log In");
        loginBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 200, 255), 2));
        loginBtn.setBorderPainted(false);
        loginBtn.setFocusPainted(false);
        loginBtn.setOpaque(true);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        rightPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 304, 290, 35));

        btnNoAcc.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        btnNoAcc.setForeground(new java.awt.Color(20, 40, 80));
        btnNoAcc.setText("Do not have a account? Register");
        btnNoAcc.setBorderPainted(false);
        btnNoAcc.setFocusPainted(false);
        rightPanel.add(btnNoAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 351, 290, 37));

        checkBox.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        checkBox.setForeground(new java.awt.Color(230, 245, 255));
        checkBox.setText("Remember me");
        checkBox.setContentAreaFilled(false);
        checkBox.setFocusPainted(false);
        rightPanel.add(checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 265, -1, -1));

        iconRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ChatGPT Image Jan 5, 2026, 08_08_07 PM.png"))); // NOI18N
        rightPanel.add(iconRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 560));

        javax.swing.GroupLayout backgPanelLayout = new javax.swing.GroupLayout(backgPanel);
        backgPanel.setLayout(backgPanelLayout);
        backgPanelLayout.setHorizontalGroup(
            backgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgPanelLayout.createSequentialGroup()
                .addComponent(lftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backgPanelLayout.setVerticalGroup(
            backgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(backgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        Register reg = new Register();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        handleLogin();
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgPanel;
    private javax.swing.JButton btnNoAcc;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel iconRight;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblForgt;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblWlcm;
    private javax.swing.JPanel lftPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
