/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;

/**
 *
 * @author pappu
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        panelSummary = new javax.swing.JPanel();
        totalSong = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSummary = new javax.swing.JTextArea();
        panelRecent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnPanel = new javax.swing.JPanel();
        btnManageCrud = new javax.swing.JButton();
        btnSearchSort = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblHomebg = new javax.swing.JLabel();
        crudPanel = new javax.swing.JPanel();
        pnlCrudTop = new javax.swing.JPanel();
        lblCrudIcon = new javax.swing.JLabel();
        lblSongs = new javax.swing.JLabel();
        scrollCrud = new javax.swing.JScrollPane();
        tblSongs = new javax.swing.JTable();
        pnlCrudBottom = new javax.swing.JPanel();
        pnlFields = new javax.swing.JPanel();
        lblSongId = new javax.swing.JLabel();
        txtSongId = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblArtist = new javax.swing.JLabel();
        txtArtist = new javax.swing.JTextField();
        lblAlbum = new javax.swing.JLabel();
        txtAlbum = new javax.swing.JTextField();
        lblGenre = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        pnlButtons = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblCrudBg = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Playlist Organizer");
        setResizable(false);

        MainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSummary.setBackground(new java.awt.Color(10, 25, 50));
        panelSummary.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true), "Summary Statistics", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(100, 191, 255))); // NOI18N
        panelSummary.setOpaque(false);

        totalSong.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        totalSong.setForeground(new java.awt.Color(255, 255, 255));
        totalSong.setText("Total Songs");

        jScrollPane1.setBackground(new java.awt.Color(15, 23, 42));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 180, 255), 2));

        txtSummary.setEditable(false);
        txtSummary.setBackground(new java.awt.Color(15, 30, 55));
        txtSummary.setColumns(20);
        txtSummary.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        txtSummary.setForeground(new java.awt.Color(220, 240, 255));
        txtSummary.setLineWrap(true);
        txtSummary.setRows(5);
        txtSummary.setWrapStyleWord(true);
        txtSummary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 180, 255)));
        txtSummary.setCaretColor(new java.awt.Color(180, 230, 255));
        txtSummary.setOpaque(false);
        jScrollPane1.setViewportView(txtSummary);

        javax.swing.GroupLayout panelSummaryLayout = new javax.swing.GroupLayout(panelSummary);
        panelSummary.setLayout(panelSummaryLayout);
        panelSummaryLayout.setHorizontalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSummaryLayout.setVerticalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        homePanel.add(panelSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 410, 440));

        panelRecent.setBackground(new java.awt.Color(8, 20, 40));
        panelRecent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2), "Recently Added", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelRecent.setForeground(new java.awt.Color(255, 255, 255));
        panelRecent.setOpaque(false);
        panelRecent.setPreferredSize(new java.awt.Dimension(418, 444));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));

        jList1.setBackground(new java.awt.Color(15, 25, 45));
        jList1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(230, 240, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { ".No Recent Songs Yet.", "Add Songs to see them here." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(60, 120, 200));
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout panelRecentLayout = new javax.swing.GroupLayout(panelRecent);
        panelRecent.setLayout(panelRecentLayout);
        panelRecentLayout.setHorizontalGroup(
            panelRecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRecentLayout.setVerticalGroup(
            panelRecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecentLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        homePanel.add(panelRecent, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 440, 440));

        btnPanel.setBackground(new java.awt.Color(5, 15, 30));
        btnPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 180, 255), 2));
        btnPanel.setForeground(new java.awt.Color(220, 235, 255));

        btnManageCrud.setBackground(new java.awt.Color(15, 25, 45));
        btnManageCrud.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnManageCrud.setForeground(new java.awt.Color(220, 235, 255));
        btnManageCrud.setText("Manage Songs");
        btnManageCrud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 180, 255), 2));
        btnManageCrud.setFocusPainted(false);
        btnManageCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCrudActionPerformed(evt);
            }
        });

        btnSearchSort.setBackground(new java.awt.Color(15, 25, 45));
        btnSearchSort.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnSearchSort.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchSort.setText("Search and Sort");
        btnSearchSort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 180, 255), 2));
        btnSearchSort.setFocusPainted(false);

        btnExit.setBackground(new java.awt.Color(15, 25, 45));
        btnExit.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 180, 255), 2));
        btnExit.setFocusPainted(false);

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnManageCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(btnSearchSort, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSort, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        homePanel.add(btnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 900, 170));

        lblHomebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/right side image.png"))); // NOI18N
        homePanel.add(lblHomebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 770));

        MainPanel.add(homePanel, "HOME");

        crudPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCrudTop.setOpaque(false);

        lblSongs.setBackground(new java.awt.Color(220, 235, 255));
        lblSongs.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblSongs.setForeground(new java.awt.Color(255, 255, 255));
        lblSongs.setText("Songs");

        scrollCrud.setBackground(new java.awt.Color(15, 25, 45));
        scrollCrud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 235), 2));
        scrollCrud.setForeground(new java.awt.Color(200, 230, 235));
        scrollCrud.setOpaque(false);

        tblSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title ", "Artist", "Album", "Genre", "Year", "Duration"
            }
        ));
        scrollCrud.setViewportView(tblSongs);

        javax.swing.GroupLayout pnlCrudTopLayout = new javax.swing.GroupLayout(pnlCrudTop);
        pnlCrudTop.setLayout(pnlCrudTopLayout);
        pnlCrudTopLayout.setHorizontalGroup(
            pnlCrudTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrudTopLayout.createSequentialGroup()
                .addGroup(pnlCrudTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCrudTopLayout.createSequentialGroup()
                        .addComponent(lblCrudIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblSongs, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        pnlCrudTopLayout.setVerticalGroup(
            pnlCrudTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrudTopLayout.createSequentialGroup()
                .addGroup(pnlCrudTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSongs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCrudIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );

        crudPanel.add(pnlCrudTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 470));

        pnlCrudBottom.setOpaque(false);

        pnlFields.setOpaque(false);

        lblSongId.setBackground(new java.awt.Color(220, 235, 255));
        lblSongId.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblSongId.setForeground(new java.awt.Color(255, 255, 255));
        lblSongId.setText("Song ID");

        txtSongId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtSongId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        txtSongId.setCaretColor(new java.awt.Color(30, 30, 30));

        lblTitle.setBackground(new java.awt.Color(220, 235, 255));
        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Title");

        txtTitle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(30, 30, 30));
        txtTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        txtTitle.setCaretColor(new java.awt.Color(30, 30, 30));
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        lblArtist.setBackground(new java.awt.Color(220, 235, 255));
        lblArtist.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblArtist.setForeground(new java.awt.Color(255, 255, 255));
        lblArtist.setText("Artist");

        txtArtist.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtArtist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        txtArtist.setCaretColor(new java.awt.Color(30, 30, 30));

        lblAlbum.setBackground(new java.awt.Color(220, 235, 255));
        lblAlbum.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblAlbum.setForeground(new java.awt.Color(255, 255, 255));
        lblAlbum.setText("Album");

        txtAlbum.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtAlbum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        txtAlbum.setCaretColor(new java.awt.Color(30, 30, 30));
        txtAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlbumActionPerformed(evt);
            }
        });

        lblGenre.setBackground(new java.awt.Color(220, 235, 255));
        lblGenre.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblGenre.setForeground(new java.awt.Color(255, 255, 255));
        lblGenre.setText("Genre");

        lblYear.setBackground(new java.awt.Color(220, 235, 255));
        lblYear.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblYear.setForeground(new java.awt.Color(255, 255, 255));
        lblYear.setText("Year");

        txtGenre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtGenre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        txtGenre.setCaretColor(new java.awt.Color(30, 30, 30));

        lblDuration.setBackground(new java.awt.Color(220, 235, 255));
        lblDuration.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblDuration.setText("Duration(sec)");

        txtYear.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        txtYear.setCaretColor(new java.awt.Color(30, 30, 30));

        txtDuration.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtDuration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        txtDuration.setCaretColor(new java.awt.Color(30, 30, 30));

        javax.swing.GroupLayout pnlFieldsLayout = new javax.swing.GroupLayout(pnlFields);
        pnlFields.setLayout(pnlFieldsLayout);
        pnlFieldsLayout.setHorizontalGroup(
            pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSongId, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(lblSongId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFieldsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(lblGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFieldsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDuration)))
                .addGap(37, 37, 37))
        );
        pnlFieldsLayout.setVerticalGroup(
            pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSongId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArtist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSongId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGenre)
                    .addComponent(txtYear)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlButtons.setOpaque(false);

        btnAdd.setBackground(new java.awt.Color(15, 25, 45));
        btnAdd.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(200, 230, 235));
        btnAdd.setText("Add");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(120, 190, 255), 2, true));
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);

        btnUpdate.setBackground(new java.awt.Color(15, 25, 45));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(200, 230, 235));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusPainted(false);

        btnDelete.setBackground(new java.awt.Color(15, 25, 45));
        btnDelete.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        btnDelete.setContentAreaFilled(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);

        btnUndo.setBackground(new java.awt.Color(15, 25, 45));
        btnUndo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnUndo.setForeground(new java.awt.Color(200, 230, 235));
        btnUndo.setText("Undo Delete (Stack)");
        btnUndo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        btnUndo.setContentAreaFilled(false);
        btnUndo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUndo.setFocusPainted(false);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(15, 25, 45));
        btnClear.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(200, 230, 235));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        btnClear.setContentAreaFilled(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(15, 25, 45));
        btnHome.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(200, 230, 235));
        btnHome.setText("Back Home");
        btnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 190, 255), 2));
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCrudBottomLayout = new javax.swing.GroupLayout(pnlCrudBottom);
        pnlCrudBottom.setLayout(pnlCrudBottomLayout);
        pnlCrudBottomLayout.setHorizontalGroup(
            pnlCrudBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrudBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCrudBottomLayout.setVerticalGroup(
            pnlCrudBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrudBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        crudPanel.add(pnlCrudBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 940, 240));

        lblCrudBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/right side image.png"))); // NOI18N
        crudPanel.add(lblCrudBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 750));

        MainPanel.add(crudPanel, "CRUD");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        MainPanel.add(searchPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCrudActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "CRUD");// TODO add your handling code here:
    }//GEN-LAST:event_btnManageCrudActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnManageCrud;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSearchSort;
    private javax.swing.JButton btnUndo;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel crudPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblCrudBg;
    private javax.swing.JLabel lblCrudIcon;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblHomebg;
    private javax.swing.JLabel lblSongId;
    private javax.swing.JLabel lblSongs;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel panelRecent;
    private javax.swing.JPanel panelSummary;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCrudBottom;
    private javax.swing.JPanel pnlCrudTop;
    private javax.swing.JPanel pnlFields;
    private javax.swing.JScrollPane scrollCrud;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tblSongs;
    private javax.swing.JLabel totalSong;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtArtist;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtSongId;
    private javax.swing.JTextArea txtSummary;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
