/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UserController;
import javax.swing.*;

/**
 *
 * @author pappu
 */
public class Register extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void handleRegister() {
        String email = txtEmail.getText().trim();
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String password = new String(fieldPassword.getPassword());
        String confirmPassword = new String(fieldConfPassword.getPassword());

        // Validation
        if (email.isEmpty() || name.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in all required fields!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this,
                    "Passwords do not match!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this,
                    "Password must be at least 6 characters!",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String gender = "";
        if (btnMale.isSelected()) {
            gender = "Male";
        } else if (btnFemale.isSelected()) {
            gender = "Female";
        }

        UserController userController = LoginForm.getUserController();

        if (userController.registerUser(email, name, phone, gender, password)) {
            JOptionPane.showMessageDialog(this,
                    "Registration successful! Please login.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Email already exists or invalid email format!",
                    "Registration Failed",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        fieldConfPassword = new javax.swing.JPasswordField();
        lblGender = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        lblPassword = new javax.swing.JLabel();
        lblConfPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        txtPhone = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnAlreadyAcc = new javax.swing.JButton();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegister.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("Register");
        jPanel1.add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 360, 40));

        lblEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(230, 245, 255));
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 330, 40));

        txtEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 510, 40));

        lblName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 265, 127, 35));

        lblPhone.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Phone");
        jPanel1.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 233, 35));

        txtName.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText(" ");
        txtName.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 37));

        fieldConfPassword.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jPanel1.add(fieldConfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 261, 40));

        lblGender.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender");
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 100, 40));

        buttonGroup1.add(btnMale);
        btnMale.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btnMale.setForeground(new java.awt.Color(230, 245, 255));
        btnMale.setText("Male");
        btnMale.setContentAreaFilled(false);
        btnMale.setFocusPainted(false);
        jPanel1.add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 80, -1));

        buttonGroup1.add(btnFemale);
        btnFemale.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        btnFemale.setForeground(new java.awt.Color(230, 245, 255));
        btnFemale.setText("Female");
        btnFemale.setContentAreaFilled(false);
        btnFemale.setFocusPainted(false);
        jPanel1.add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, -1));

        lblPassword.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 188, 38));

        lblConfPassword.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblConfPassword.setForeground(new java.awt.Color(120, 220, 255));
        lblConfPassword.setText("Confirm Password");
        jPanel1.add(lblConfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 261, 38));

        fieldPassword.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 210, 40));

        txtPhone.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 262, 37));

        btnLogin.setBackground(new java.awt.Color(10, 30, 70));
        btnLogin.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Register");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 220, 255), 2));
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 370, 50));

        btnAlreadyAcc.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnAlreadyAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnAlreadyAcc.setText("Already have an account? Log In");
        btnAlreadyAcc.setBorderPainted(false);
        btnAlreadyAcc.setContentAreaFilled(false);
        btnAlreadyAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlreadyAccActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlreadyAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 370, 50));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ChatGPT Image Jan 5, 2026, 08_08_07 PM.png"))); // NOI18N
        jPanel1.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlreadyAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlreadyAccActionPerformed
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnAlreadyAccActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        handleRegister();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlreadyAcc;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JButton btnLogin;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField fieldConfPassword;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblConfPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
